<!-- Ad Maiorem Dei Gloriam-->

<script setup>

    import FileInput from './FileInput.vue';
import ROM from './ROM.vue';

    const roms = [
        {
            title: "Animal Race",
            icon: "icon",
            description: "Race with another animals!",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtCm4CaA5pC6W1JIJoLCSEaB1pGCSEawBsIyRYJMBoIWkApNj7HtiU/hh7BEscawR8/yTAPAASGgDg+RgkWCTAagBrCqYA+h73ZWIMdAH7KdJFYhPzKdJFYhemoNJFegh7ATooEkRoIGkCpeIkgGImYwjSN6X9/TPyZWMsZAlAABKI8CnTRRKMQQASkvEpYzHTRfIpYzbTRaaAaCRpESSEaDampdiVbwr/FSRKMBASuP8HPwASqhKk/hiMAGoJisVPARKkTA8SpNiVTwASyPwp2JUkoKX2YyxkF9NHYzZkGKal00VvCv8VJEowEBL2/wc/ABLoEuL+GIsAitCKtU8AEuJLABLiagmKtU8AEuLTRU8AEw77KdNFJJQA4CTAJKCk1mA4YQDQEXEBMSATJmAeYQ9qA/op0BX+GCSUev/QFToAEzRqAKYA+h72ZaYA+h5w/0AAE1rwVRNywAFwApFQgWVxBnIB8lWlAPEe0kZCOBOAeghKGP4YOigTRv4YE0TyGGgGaQil4iSEh6aHdod2dwqXwBPAppQkhCSy+ymNtdiVPQAT7iSQ2JUksqUlaAhpA9iVbxAkltiVifMTsgDupookhCSypgD6HvZlZwCHtHP/MwATzqX99zPyZUEAE+TxKSSG8inYlY10TwEUDKYA+h72ZaUA8R7SRW8Y/xX/ByRKMBASOD8AE/4T+CSQAOBkDmIAYUCl4mgGaQgkhKaKJISmAPEe0khyATJAFDZ0CTQgFBIUDnEIQXhhSG0HjSJNABQWbwQklhQiYADgoQDucAFAEADuFEymAGEAZgQkZiRmJGYkZsABcAHCA4cuYwaDdccBg3SDBPNVcST2HgDuJIYkhiSG2JVvBf8eeAgA7iSSJJRvPP8Y/wc/ABSYAO6mnmgAic6JnomeicV5u9iSAO6l9mgIaRDYl2gQaREA7moApgD6HvRlpQDxHtJGegg6KBTCAO4BAYF+GACZQtsAAACBgQAAAMM8ZhhCQsNCAOfnAAAA7o6Kioru7ojsKO4DAgIOCgoFBgYSHgUFBgYSHigFBgYSHhAFBgYSHgIFBgYSHgUAPz89JSQAQUFHbgoAQUFHbZAAQUFHbwAAQUFHbhIAQUFHbZAAAwYOFCYABQoiIEADAAJoNhgGDxoWSAMABQpCDAAABQpCAAAACx4+IiIAHSJCZgUAHSJCZoAAHSJCZhAAHSJCZggAHSJCZgEAAhMeEhICFzguBiQEJC86VhEABjUiNigABjUiNgACFzguBigB6a3rqalRW1VRUXRUdFRX95X3pZV3REZEd++oruK+85KTkp8XFRcREXcVFxUXKyoSEhOoqKiouK6q7qqqrqiuqE4geKBwKPAgAAEAAgADAgAeGAABJAMBBkISAAFIAAgNZhgAAmgDAxOKGAABkAMBGq4YAAEIOAYAGBgBAQQxAAUYGAF/SBwcC0wYAAMCAg5eBCZUBQYG0qJM5sEFBsbS4sy4kAWGBlIiTF5gBQaG0qKMxsEFBoaSIoyYMAAGBhJiDD4QAO5jGiTAAO7wkPeQkHhAcEB4q6mpqVOiMiomoo6Kioru7ojsKO4AwBhICEgc4CBgAEA="
        },
        {
            title: "Breakout",
            icon: "icon",
            description: "A game where you battle with briksss!",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABuBWUAawZqAKMM2rF6BDpAEgh7AjsSEgZsIG0foxDc0SL2YABhAKMS0BFwCKMO0BFgQPAV8AcwABI0xg9nHmgBaf+jDtZxoxDc0WAE4KF8/mAG4KF8AmA/jALc0aMO1nGGhIeUYD+GAmEfhxJHHxKsRgBoAUY/aP9HAGkB1nE/ARKqRx8SqmAFgHU/ABKqYAHwGIBgYfyAEqMM0HFg/okDIvZ1ASL2RWAS3hJGaf+AYIDFPwESymECgBU/ARLggBU/ARLugBU/ARLoYCDwGKMOfv+A4IAEYQDQET4AEjAS3nj/SP5o/xLueAFIAmgBYATwGGn/EnCjFPUz8mXxKWM3ZADTRXMF8inTRQDu8ACAAPwAqgAAAAAA"
        },
        {
            title: "Cave",
            icon: "icon",
            description: "Like a pacman! 2 - Up, 4 - Left, 6 - Right, 8 - Down",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GQAZQCiChIMzDNmHtRS1GJ0CERAEhoSDqIeEiz//8DAwMDAwMDAwMD//2QNZQnUXnQKojrUXhJI///Dw8PDw///w8PDw8N0CqJQ1F4SXsPDw8PDZmZmZmY8PBgYdAqiZtReEnT//8DAwMD//8DAwMD//2oBawRsDm0AooESpoD///////////8A4GQAZQDUWHQIREAinkUgEqQSkGQAdQgA7hKuYA/gnhKoEopKASLQSgIjikoDI7hKBCPgSgUkGEoGJHhKByTmSgglEBMYooFkAmUC1FhlCtRYZRLUWGQKZQXUU2QS1FNkGtRTZCLUU2Qq1FNkMtRTov4TCvz8/Pz8/Pz8/Pz8/HUDdALUXHQGdQnUUwDuooDbwU8BE3JgAuChbQJgBOChbQRgBuChbQZgCOChbQjbwU0CfP9NBHv/TQZ7AU0IfAFLQBNeS/8TZGAC8BXwBzAAE1YTGHoBSgkVOmsBooESinr/az6igRKKYAPwGGAP4J4TeGoBawRsDm0AooEA4BKKZABlEaKB1FN0CNRTdAh1/9RTdAh1/9RTdAjUU3QI1FN0CHUB1FN0CHUB1FMA7mQAZRGigdRTdAjUU3QIdQLUUnQI1FF0CNRRdAjUUXQI1FF0CNRRAO5kAGUTooHUUaKAdAjUUXUB1FF1AaKB1FF0CNRRdAjUUnQIdf/UU3QI1FR0CHX/1FZ0CHX/1FgA7mQAZRKigdRYdAjUWHQI1Fh0CNRYdAjUWHQI1Fh0CNRYooB1/3Qg1FF1/9RRdf/UUXX/1FF1/9RRdf/UUXX/1FF1/9RRdf+igdRRdAjUUXQI1FF0CNRRdAjUUXQI1FEA7mQAZQmigdRRdAjUUXQI1FF0CNRRdAjUUXQI1FGigHUB1FF1AdRRdQHUUXUB1FF1AdRRdQHUUXUB1FF1AdRRdQHUUXUB1FF1AdRRdQHUUXUB1FF1AdRRdQHUUXUB1FF1AaKB1FF0CNRRdAjUUQDuZABlGqKB1FF0CNRRdAjUUXQI1FF0CNRRdf/UUXQI1FF0CNRRdAjUUQDuZABlGaKB1FF0CNRRdAjUUXQI1FF0CNRRdf/UUXQI1FF0CNRRdAjUUQDuAOBnA2gDpUQVXK6q6kpOAKSkpKXiAF1VVVWdAMhISEBIANeFpUp3CNeFdwilUNeFdwilVteFFXA="
        },
        {
            title: "Pong",
            icon: "icon",
            description: "Pong Gameeee! 1 - Up player1, 4 - Down player1, C - Up player2, D - Down player2!",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "Loaded this rom: 8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqAmsMbD9tDKLq2rbc1m4AItRmA2gCYGDwFfAHMAASGscXdwhp/6Lw1nGi6tq23NZgAeChe/5gBOChewJgH4sC2rZgDOChff5gDeChfQJgH40C3Nai8NZxhoSHlGA/hgJhH4cSRgISeEY/EoJHH2n/RwBpAdZxEipoAmMBgHCAtRKKaP5jCoBwgNU/ARKiYQKAFT8BErqAFT8BEsiAFT8BEsJgIPAYItSONCLUZj4zAWYDaP4zAWgCEhZ5/0n+af8SyHkBSQJpAWAE8Bh2AUZAdv4SbKLy/jPyZfEpZBRlANRVdBXyKdRVAO6AgICAgICAAAAAAAA="
        },
        {
            title: "Puzzle",
            icon: "icon",
            description: "OOOhhh, what could it be?",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqEmsBYRBiAGAAorDRJ/ApMADatXEIeggxMBIkYRByCGoSewijAPAe8FVwATAQEgpqEmsBbABi/8AGcAIiUnL/MgASOG4AbgDwCiJSfgF+ARJIhKCFsIbAMAISZEUBEmR1+Hb8MAgScEUZEnB1CHYEMAYSfEQSEnx0+Hb/MAQSiEQqEoh0CHYBowD2HvBlgQBgAKMA9h7wVaMA/B6AEPBV8SnUVdq1ikCLUIxgAO7uXv7+/v7+/v7+"
        },
        {
            title: "Soccer",
            icon: "icon",
            description: "A niceeee soccer Game!!",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GoMawxoAGkAZgBnAGUAZACjSCMiIzQjPmBg8BXwB0AAEiYSHmQCZgJnECMIItQjCCMMRkASXEb+EoAjCE8BIuRgAeChIqRgBOChIrBgDOChIrxgDeChIsgSMCMieAFICmgAIyJgFPAYZgJnEGQCItQjCGBg8BXwB0AAEjASeCMieQFJCmkAIyJgFPAYZjpnEGT+ItQjCGBg8BXwB0AAEjASnEoAAO4jNHr+IzQA7koaAO4jNHoCIzQA7ksAAO4jPnv+Iz4A7ksaAO4jPnsCIz4A7sADQABl/0ABZQBAAmUBAO5GABL2RhQS9kYoEvZGPBL2AO4i1GAE8BhE/hMEZP4A7mQCAO7WcQDuhkSHVEcAExpHHxMeAO5lAQDuZf8A7mEVYAD4KdEFcRT5KdEFo0gA7mEA0aZxKNGmAO5hFNG2cSjRtgDugICAgICA"
        },
        {
            title: "Space Invaders",
            icon: "icon",
            description: "A LEGENDARY Game!",
            credits: "Credits: https://github.com/kripod/chip8-roms",
            content: "8JCQkPAgYCAgcPAQ8IDw8BDwEPCQkPAQEPCA8BDw8IDwkPDwECBAQPCQ8JDw8JDwEPDwkPCQkOCQ4JDg8ICAgPDgkJCQ4PCA8IDw8IDwgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASJVNQQUNFIElOVkFERVJTIDAuOTEgQnkgRGF2aWQgV0lOVEVSYABhAGIIo93QGHEI8h4xIBItcAhhADBAEi1pBWwVbgAjkWAK8BXwBzAAEksjkX4BEkVmAGgcaQBqBGsKbARtPG4PAOAjdSNR/RVgBOCeEn0jdTgAeP8jdWAG4J4SiyN1ODl4ASN1NgASn2AF4J4S6WYBZRuEgKPZ1FGj2dRRdf81/xKtZgAS6dRRPwES6dRRZgCDQHMDg7Vi+IMiYggzABLJI32CBkMIEtMzEBLVI32CBjMYEt0jfYIGQyAS5zMoEukjfT4AEwd5BkkYaQBqBGsKbAR99G4PAOAjUSN1/RUSb/cHNwASb/0VI1GLpDsSExt8Amr8OwITI3wCagQjUTwYEm8A4KTdYBRhCGIP0B9wCPIeMCwTM2D/8BXwBzAAE0HwCgDgpwb+ZRIlo8H5HmEII2mBBiNpgQYjaYEGI2l70ADugOCAEjAA28Z7DADuo9lgHNgEAO4jUY4jI1FgBfAY8BXwBzAAE4kA7moAjeBrBOmhElemDP0e8GUw/xOvagBrBG0BbgETl6UK8B7bxnsIfQF6AToHE5cA7jx+//+ZmX7//yQk537/PDx+24FCPH7/2xA4fP4AAH8APwB/AAAAAQEBAwMDAwAAPyAgICAgICAgPwgI/wAA/gD8AP4AAAB+QkJiYmJiAAD/AAAAAAAAAAD/AAD/AH0AQX0FfX0AAMLCxkRsKDgAAP8AAAAAAAAAAP8AAP8A9xAU9/cEBAAAfET+wsLCwgAA/wAAAAAAAAAA/wAA/wDvICjo6C8vAAD5hcXFxcX5AAD/AAAAAAAAAAD/AAD/AL4AIDAgvr4AAPcE54WFhPQAAP8AAAAAAAAAAP8AAP8AAH8APwB/AAAA7yjvAOBgbwAA/wAAAAAAAAAA/wAA/wAA/gD8AP4AAADAAMDAwMDAAAD8BAQEBAQEBAT8EBD/+YG5i5qa+gD6ipqam5n45iUl9DQ0NAAXFDQ3NibH31BQXNjY3wDfER8SGxnZfET+hoaG/IT+goL+/oDAwMD+/ILCwsL8/oD4wMD+/oDwwMDA/oC+hob+hob+hoaGEBAQEBAQGBgYSEh4nJCwwLCcgIDAwMD+7pKShoaG/oKGhoaGfIKGhoZ8/oL+wMDAfILCysR6/ob+kJyE/sD+AgL+/hAwMDAwgoLCwsL+goKC7jgQhoaWkpLugkQ4OESCgoL+MDAw/gIe8ID+AAAAAAYGAAAAYGDAAAAAAAAAGBgYGAAYfMYMGAAYAAD+/gAA/oKGhob+CAgIGBgY/gL+wMD+/gIeBgb+hMTE/gQE/oD+Bgb+wMDA/oL+/gICBgYGfET+hob+/oL+BgYGRP5ERP5EqKioqKioqGxaAAwYqDBOfgASGGZsqFpmVCRmAEhIGBKoBpCoEgB+MBKohDBOchhmqKioqKiokFR4qEh4bHKoEhhscmZUkKhyKhioME5+ABIYZmyoclSoWmYYfhhOcqhyKhgwZqgwTn4AbDBUTpyoqKioqKioSFR+GKiQVHhmqGwqMFqohDByKqjYqABOEqjkoqgAThKobCpUVHKohDByKqjenKhyKhioDFRIWnhyGGaoZhhaVGZybKhyKgByqHIqGKgwTn4AEhhmbKgAZhioME4MZhgAbDBOJKhyKhgwZqgeVGYMGJyoJFRUEqhCeAw8qK6oqKioqKio/wAAAAAAAAAAAAAAAAAAAA=="
        },

    ];
</script>

<template>
    <div class="roms-section">
        <div class="rom">
            <FileInput/>
        </div>
        <div class="rom" v-for="rom in roms">
            <ROM :name="rom.title" :icon="rom.icon" :content="rom.content">
                {{ rom.description }} 
                <br>
                <br>
                {{ rom.credits }}
            </ROM>
        </div>
    </div>
</template>

<style>
    .roms-section {
        display: grid;
        justify-items: center;
        gap: 2rem;
        grid-template-columns: repeat(3, 20rem);

        min-width: fit-content;
    }

    @media (width < 1024px) {
        .roms-section {
            grid-template-columns: 20rem 20rem;
        }
    }
    @media (width < 720px) {
        .roms-section {
            grid-template-columns: 20rem;
        }
    }
</style>